[project]
name = "logistics-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["fastapi","uvicorn[standard]","pydantic-settings","orjson","sqlalchemy","asyncpg","alembic","websockets","python-dotenv"]