version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics
    ports: ['5432:5432']
  redis:
    image: redis:7
    ports: ['6379:6379']